# ~/.bashrc - Rebuntu default

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# Colorful ls and grep
alias ls='ls --color=auto'
alias ll='ls -lahF'
alias grep='grep --color=auto'

# More comfortable history
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
PROMPT_COMMAND='history -a'

export EDITOR="code"
export SUDO_EDITOR="nvim"

# Set complete path
export PATH="./bin:$HOME/.local/bin:$HOME/.local/share/rebuntu/bin:$PATH"
set +h

# A simple, colorful prompt
PS1='\[\033[01;32m\]\u@\h \[\033[01;34m\]\w\$ \[\033[00m\]'

set meta-flag on
set input-meta on
set output-meta on
set convert-meta off
set completion-ignore-case on
set completion-prefix-display-length 2
set show-all-if-ambiguous on
set show-all-if-unmodified on

# Arrow keys match what you've typed so far against your command history
"\e[A": history-search-backward
"\e[B": history-search-forward
"\e[C": forward-char
"\e[D": backward-char

# Immediately add a trailing slash when autocompleting symlinks to directories
set mark-symlinked-directories on

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Show all autocomplete results at once
set page-completions off

# If there are more than 200 possible completions for a word, ask to show them all
set completion-query-items 200

# Show extra file information when completing, like `ls -F` does
set visible-stats on

$if Bash
  # Be more intelligent when autocompleting by also looking at the text after
  # the cursor. For example, when the current line is "cd ~/src/mozil", and
  # the cursor is on the "z", pressing Tab will not autocomplete it to "cd
  # ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
  # Readline used by Bash 4.)
  set skip-completed-text on

  # Coloring for Bash 4 tab completions.
  set colored-stats on
$endif